export { main } from "./cli.js";
export {
  assertUniqueArtifactIdentities,
  canonicalizeMetadata,
  digestBytes,
  digestMetadata,
  inspectRetainedArtifact,
  readVerifiedArtifact,
  SUPPORTED_ARTIFACT_SCHEMA_VERSIONS,
  validateArtifact,
  validateExportManifest,
  validateRunManifestEvidence,
  verifyDigest,
  writeArtifactAtomically,
  writeMetadataAtomically,
} from "./artifacts.js";
export type { ArtifactIdentity, ArtifactValidationError } from "./artifacts.js";
export {
  assertAdmittedTaskPackets,
  assertArchiveMeasurements,
  assertControlledPerturbationDigest,
  assertDeclaredOrder,
  assertNoSelectedSymlinks,
  assertResolvedExperimentConfigurationDigests,
  declaredMatrixCells,
  isSafeArtifactRelativePath,
  MAX_CONFIGURATION_BYTES,
  resolveBundleConfiguration,
  resolveBundleArtifact,
  resolveBundleArtifactDigest,
  resolveTaskArchive,
  readTaskArchive,
  validateTaskArchive,
} from "./contracts.js";
export {
  admitTaskPacket,
  assertTaskPacketFreezeRecord,
  assertTaskPacketAdmitted,
  defaultFreezeLocator,
  formatErrors,
  freezeTaskPacket,
  inspectTaskPacket,
  modelVisibleTaskPacket,
  statusTaskPacket,
  MAX_TASK_PACKET_METADATA_BYTES,
  TASK_PACKET_FREEZE_SCHEMA_VERSION,
} from "./task-packets.js";
export type { TaskPacket, TaskPacketComponent, TaskPacketComponents, TaskPacketFreezeRecord, TaskPacketInspection, TaskPacketStatus } from "./task-packets.js";
export type {
  ArtifactReference,
  AssessmentMode,
  ArchiveEntry,
  ArchiveLimits,
  ArchiveMeasurements,
  ControlledPerturbationDeclaration,
  DeclaredOrder,
  DeclaredMatrixCell,
  Digest,
  ExperimentConfiguration,
  ExperimentOrdering,
  ReferenceSolutionDeclaration,
  ResolvedTaskPacket,
  TaskCondition,
  TaskConditionSet,
  TaskArchiveEntry,
} from "./contracts.js";
export {
  assertValidRunQueue,
  compileRunQueue,
  expandMatrixCells,
  inspectRunQueue,
  LocalRunQueue,
  MAX_RUN_QUEUE_BYTES,
  MAX_RUN_QUEUE_ENTRIES,
  readRunQueue,
  validateRunQueue,
  writeRunQueue,
} from "./scheduler.js";
export type {
  CompileRunQueueOptions,
  FrozenTaskIdentity,
  FrozenTaskInput,
  PermutationAlgorithm,
  QueueOrderingStrategy,
  RunQueue,
  RunQueueEntry,
  RunQueueInspection,
  RunQueueMatrix,
  ValidateRunQueueOptions,
} from "./scheduler.js";
export {
  digestWorkspace,
  digestWorkspaceTree,
  executeVerifier,
  serializeVerifierResult,
  writeVerifierResult,
} from "./verifiers.js";
export type {
  CompleteVerifierResult,
  DiagnosticOrigin,
  DiagnosticReference,
  ExecuteVerifierOptions,
  VerifierAssertion,
  VerifierAssertionStatus,
  VerifierErrorResult,
  VerifierExecutionReference,
  VerifierFailedResult,
  VerifierNotRunResult,
  VerifierNotRunAssertion,
  VerifierPassedAssertion,
  VerifierPassedResult,
  VerifierResult,
  VerifierRunResult,
  VerifierWorkspace,
} from "./verifiers.js";
export { cleanupWorkspace, materializeWorkspace } from "./workspaces.js";
export type {
  WorkspaceMaterialization,
  WorkspaceMaterializationOptions,
  WorkspaceSetupContext,
  WorkspaceSetupStep,
} from "./workspaces.js";
export {
  createAttemptIdentity,
  createRunIdentity,
  executeRunAttempt,
  InvalidLifecycleTransitionError,
  LifecycleController,
  retryAttempt,
  readAttemptRecord,
  writeAttemptRecord,
} from "./lifecycle.js";
export type {
  AttemptClassification,
  AttemptClassificationKind,
  AttemptIdentity,
  AttemptRecord,
  EvidenceSink,
  FailureClass,
  HarnessExecutionContext,
  HarnessExecutionResult,
  HarnessExecutor,
  HarnessShutdownResult,
  LifecycleSnapshot,
  LifecycleState,
  LifecycleTransition,
  RunAttemptOptions,
  RunAttemptResult,
  RunIdentity,
  StopReason,
  TerminalRecord,
  TerminalState,
  VerifierExecutionContext,
  VerifierExecutionResult,
  VerifierExecutor,
  VerifierShutdownResult,
  WorkspaceCleanupContext,
  WorkspaceCoordinator,
  WorkspaceExecutionResult,
  WorkspaceShutdownResult,
  WorkspaceSetupContext as LifecycleWorkspaceSetupContext,
} from "./lifecycle.js";
export {
  createRunBundleAssembler,
  qualifyRunBundle,
  RunBundleAssembler,
} from "./run-bundles.js";
export type {
  AgentSdkQualificationEvidence,
  CaptureQualificationDimension,
  CaptureQualificationOptions,
  CaptureQualificationReason,
  CaptureQualificationReasonCode,
  CaptureQualificationReport,
  CaptureQualificationStatus,
  CapturedWorkspaceOutcome,
  CaptureMissingEvidence,
  CaptureWorkspaceOutcomeOptions,
  RegisterRunBundleArtifact,
  RunBundleConfiguration,
  RunBundleDefinition,
  RunBundleEvidenceDescriptor,
  RunBundleRun,
  RunBundleRuntimeComponent,
  RunManifest,
} from "./run-bundles.js";
export { createPortableRunBundleExport, readPortableRunBundleExport } from "./exports.js";
export type {
  CreatePortableRunBundleExportOptions,
  PortableExportArtifact,
  PortableExportManifest,
  PortableExportPolicy,
} from "./exports.js";
export {
  buildCorpusIndex,
  packPortableExport,
  queryCorpusIndex,
  readCorpusIndex,
  unpackPortableExport,
  validateCorpusIndex,
  writeCorpusIndex,
} from "./corpus.js";
export type {
  CorpusIndexEntry,
  CorpusIndexQuery,
  CorpusIndexValidationIssue,
  CorpusSourceIssue,
} from "./corpus.js";
export {
  BoundedDiagnosticCapture,
  JsonlEvidenceWriter,
  openJsonlEvidenceWriter,
  ProtocolEvidenceRecorder,
  ProtocolProcess,
  runProtocolProcess,
  spawnProtocolProcess,
} from "./process-protocol.js";
export {
  createDeepSeekHarnessAdapter,
  createDeepSeekRuntimeComposition,
  DEEPSEEK_ADAPTER_ID,
  DEEPSEEK_CAPABILITY_PROFILE,
  DEEPSEEK_HARNESS_ID,
  DEEPSEEK_SDK_VERSION,
  deepSeekCapabilities,
  deepSeekCompositionDigest,
  DeepSeekNativeCapture,
  executeDeepSeekHarness,
  normalizeDeepSeekCapture,
  qualifiedDeepSeekCapture,
} from "./deepseek-adapter.js";
export type {
  DeepSeekAdapterRequest,
  DeepSeekCapabilities,
  DeepSeekCaptureReport,
  DeepSeekFileReference,
  DeepSeekHarnessConfiguration,
  DeepSeekNativeObservation,
  DeepSeekRuntimeComposition,
  DeepSeekRuntimeCompositionInput,
} from "./deepseek-adapter.js";
export {
  buildClaudeAgentSdkEnvironment,
  executeClaudeAgentSdk,
  openClaudeAgentSdkHookCapture,
  openClaudeAgentSdkStreamCapture,
  probeClaudeAgentSdkCapabilities,
} from "./agent-sdk.js";
export type {
  ClaudeAgentSdkQuery,
  ClaudeAgentSdkQueryHandle,
  ClaudeAgentSdkEnvironment,
  ClaudeAgentSdkCaptureWarnings,
  ClaudeAgentSdkCaptureReport,
  ClaudeAgentSdkCapabilities,
  ClaudeAgentSdkConfiguration,
  ClaudeAgentSdkEvidenceSink,
  ClaudeAgentSdkHookCapture,
  ClaudeAgentSdkHookRecord,
  ClaudeAgentSdkLifecycleEvent,
  ClaudeAgentSdkMessageDiagnostic,
  ClaudeAgentSdkMessageRecord,
  ClaudeAgentSdkStreamCapture,
  ClaudeAgentSdkAttemptEvidence,
  ClaudeAgentSdkTelemetryConfiguration,
  ClaudeAgentSdkTelemetryCorrelation,
  ClaudeAgentSdkTelemetryEvidence,
  ClaudeAgentSdkTelemetryReceipt,
  ClaudeAgentSdkTelemetrySignal,
} from "./agent-sdk.js";
export { captureClaudeAgentSdkRun } from "./agent-sdk-run.js";
export type {
  CaptureClaudeAgentSdkRunOptions,
  CaptureClaudeAgentSdkRunResult,
  CaptureClaudeAgentSdkVerifier,
} from "./agent-sdk-run.js";
export {
  AdapterRegistry,
  assertAdapterContract,
  UNIFORM_EVENT_FAMILIES,
  validateUniformEvents,
} from "./uniform-events.js";
export type {
  AdapterCapability,
  AdapterCapabilityProfile,
  CapturedNativeRecord,
  ContentReference,
  EvidenceUnavailable,
  EvidenceValue,
  HarnessAdapter,
  NativeCaptureAdapter,
  NativeEvidenceReference,
  NativeEvidenceResolver,
  NativeOrderEvidence,
  NormalizationInput,
  NormalizationResult,
  QualifiedNativeCapture,
  UniformAttributeScalar,
  UniformAttributeValue,
  UniformEvent,
  UniformEventFamily,
  UniformEventNormalizationAdapter,
  UnmappedNativeRecord,
} from "./uniform-events.js";
export {
  CLAUDE_AGENT_SDK_HARNESS,
  CLAUDE_AGENT_SDK_NORMALIZATION_ADAPTER_ID,
  claudeAgentSdkNormalizationAdapter,
  createAgentSdkNativeEvidenceResolver,
  normalizeClaudeAgentSdkRunBundle,
  readQualifiedClaudeAgentSdkCapture,
} from "./agent-sdk-normalizer.js";
export type {
  AgentSdkNativeRecord,
  AgentSdkNormalizationResult,
} from "./agent-sdk-normalizer.js";
export {
  AGENT_SDK_CONFIG_SCHEMA_VERSION,
  resolveAgentSdkConfigurationRecord,
  runAgentSdkQueueEntry,
} from "./agent-sdk-runner.js";
export type {
  AgentSdkCaptureProfileConfiguration,
  AgentSdkConfigurationKind,
  AgentSdkConfigurationRecord,
  AgentSdkHarnessConfiguration,
  AgentSdkModelConfiguration,
  AgentSdkNativeLimitsConfiguration,
  AgentSdkNativeToolPolicyConfiguration,
  AgentSdkRunSummary,
  RunAgentSdkQueueEntryOptions,
} from "./agent-sdk-runner.js";
export type {
  BoundedDiagnostic,
  JsonlEvidenceWriterOptions,
  ProcessTermination,
  ProtocolCapability,
  ProtocolCompletionEvidence,
  ProtocolIdentity,
  ProtocolObservation,
  ProtocolObservationInput,
  ProtocolObservationKind,
  ProtocolProcessOptions,
  ProtocolProcessResult,
} from "./process-protocol.js";
