export { main } from "./cli.js";
export {
  assertUniqueArtifactIdentities,
  canonicalizeMetadata,
  digestBytes,
  digestMetadata,
  readVerifiedArtifact,
  SUPPORTED_ARTIFACT_SCHEMA_VERSIONS,
  validateArtifact,
  validateExportManifest,
  validateRunManifestEvidence,
  verifyDigest,
  writeMetadataAtomically,
} from "./artifacts.js";
export type { ArtifactIdentity, ArtifactValidationError } from "./artifacts.js";
export {
  assertAdmittedTaskPackets,
  assertArchiveMeasurements,
  assertControlledPerturbationDigest,
  assertDeclaredOrder,
  assertNoSelectedSymlinks,
  assertResolvedExperimentConfigurationDigests,
  declaredMatrixCells,
  isSafeArtifactRelativePath,
  MAX_CONFIGURATION_BYTES,
  resolveBundleConfiguration,
  resolveBundleArtifact,
  resolveBundleArtifactDigest,
  resolveTaskArchive,
  readTaskArchive,
  validateTaskArchive,
} from "./contracts.js";
export {
  admitTaskPacket,
  assertTaskPacketFreezeRecord,
  assertTaskPacketAdmitted,
  defaultFreezeLocator,
  formatErrors,
  freezeTaskPacket,
  inspectTaskPacket,
  modelVisibleTaskPacket,
  statusTaskPacket,
  MAX_TASK_PACKET_METADATA_BYTES,
  TASK_PACKET_FREEZE_SCHEMA_VERSION,
} from "./task-packets.js";
export type { TaskPacket, TaskPacketComponent, TaskPacketComponents, TaskPacketFreezeRecord, TaskPacketInspection, TaskPacketStatus } from "./task-packets.js";
export type {
  ArtifactReference,
  ArchiveEntry,
  ArchiveLimits,
  ArchiveMeasurements,
  ControlledPerturbationDeclaration,
  DeclaredOrder,
  DeclaredMatrixCell,
  Digest,
  ExperimentConfiguration,
  ExperimentOrdering,
  ReferenceSolutionDeclaration,
  ResolvedTaskPacket,
  TaskCondition,
  TaskConditionSet,
  TaskArchiveEntry,
} from "./contracts.js";
export {
  assertValidRunQueue,
  compileRunQueue,
  expandMatrixCells,
  inspectRunQueue,
  LocalRunQueue,
  MAX_RUN_QUEUE_BYTES,
  MAX_RUN_QUEUE_ENTRIES,
  readRunQueue,
  validateRunQueue,
  writeRunQueue,
} from "./scheduler.js";
export type {
  CompileRunQueueOptions,
  FrozenTaskIdentity,
  FrozenTaskInput,
  PermutationAlgorithm,
  QueueOrderingStrategy,
  RunQueue,
  RunQueueEntry,
  RunQueueInspection,
  RunQueueMatrix,
  ValidateRunQueueOptions,
} from "./scheduler.js";
export {
  digestWorkspace,
  executeVerifier,
  serializeVerifierResult,
  writeVerifierResult,
} from "./verifiers.js";
export type {
  CompleteVerifierResult,
  DiagnosticOrigin,
  DiagnosticReference,
  ExecuteVerifierOptions,
  VerifierAssertion,
  VerifierAssertionStatus,
  VerifierErrorResult,
  VerifierExecutionReference,
  VerifierFailedResult,
  VerifierNotRunResult,
  VerifierNotRunAssertion,
  VerifierPassedAssertion,
  VerifierPassedResult,
  VerifierResult,
  VerifierRunResult,
  VerifierWorkspace,
} from "./verifiers.js";
export { cleanupWorkspace, materializeWorkspace } from "./workspaces.js";
export type {
  WorkspaceMaterialization,
  WorkspaceMaterializationOptions,
  WorkspaceSetupContext,
  WorkspaceSetupStep,
} from "./workspaces.js";
export {
  createAttemptIdentity,
  createRunIdentity,
  executeRunAttempt,
  InvalidLifecycleTransitionError,
  LifecycleController,
  retryAttempt,
  readAttemptRecord,
  writeAttemptRecord,
} from "./lifecycle.js";
export type {
  AttemptClassification,
  AttemptClassificationKind,
  AttemptIdentity,
  AttemptRecord,
  EvidenceSink,
  FailureClass,
  HarnessExecutionContext,
  HarnessExecutionResult,
  HarnessExecutor,
  HarnessShutdownResult,
  LifecycleSnapshot,
  LifecycleState,
  LifecycleTransition,
  RunAttemptOptions,
  RunAttemptResult,
  RunIdentity,
  StopReason,
  TerminalRecord,
  TerminalState,
  VerifierExecutionContext,
  VerifierExecutionResult,
  VerifierExecutor,
  VerifierShutdownResult,
  WorkspaceCleanupContext,
  WorkspaceCoordinator,
  WorkspaceExecutionResult,
  WorkspaceShutdownResult,
  WorkspaceSetupContext as LifecycleWorkspaceSetupContext,
} from "./lifecycle.js";
export {
  BoundedDiagnosticCapture,
  JsonlEvidenceWriter,
  openJsonlEvidenceWriter,
  ProtocolEvidenceRecorder,
  ProtocolProcess,
  runProtocolProcess,
  spawnProtocolProcess,
} from "./process-protocol.js";
export { buildClaudeAgentSdkEnvironment, executeClaudeAgentSdk, openClaudeAgentSdkStreamCapture, probeClaudeAgentSdkCapabilities } from "./agent-sdk.js";
export type {
  ClaudeAgentSdkEnvironment,
  ClaudeAgentSdkCaptureReport,
  ClaudeAgentSdkCapabilities,
  ClaudeAgentSdkConfiguration,
  ClaudeAgentSdkEvidenceSink,
  ClaudeAgentSdkLifecycleEvent,
  ClaudeAgentSdkMessageDiagnostic,
  ClaudeAgentSdkMessageRecord,
  ClaudeAgentSdkStreamCapture,
  ClaudeAgentSdkAttemptEvidence,
  ClaudeAgentSdkTelemetryConfiguration,
  ClaudeAgentSdkTelemetryCorrelation,
  ClaudeAgentSdkTelemetryEvidence,
  ClaudeAgentSdkTelemetryReceipt,
  ClaudeAgentSdkTelemetrySignal,
} from "./agent-sdk.js";
export type {
  BoundedDiagnostic,
  JsonlEvidenceWriterOptions,
  ProcessTermination,
  ProtocolCapability,
  ProtocolCompletionEvidence,
  ProtocolIdentity,
  ProtocolObservation,
  ProtocolObservationInput,
  ProtocolObservationKind,
  ProtocolProcessOptions,
  ProtocolProcessResult,
} from "./process-protocol.js";
